# Generated by Django 5.1.3 on 2024-11-16 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_remove_vehicle_is_repair_alter_issue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.component'),
        ),
    ]
