# Generated by Django 5.1.3 on 2024-11-16 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_issue_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.component'),
        ),
    ]
