# Generated by Django 5.1.3 on 2024-11-16 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_issue_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='created_at',
        ),
    ]
